version: 1
groups:
  main:
    help: This is the main group, let's have fun
    targets:
      favorite-food:
        help: What is your favorite food?
        args:
          food:
            help: the name of the food
            type: string
            required: true
        run: |
          echo "my favorite food is {{ args.food }}"
      favorite-dessert:
        help: What is your favorite dessert?
        dependencies:
          - target: main.favorite-food
            args:
              food: pizza
          - target: main.favorite-food
            args:
              food: lasagna
        args:
          dessert:
            help: What is your favorite dessert?
            type: string
            required: false
            default: tiramisu
        run: |
          echo "my favorite dessert is {{ args.dessert }}"
